<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="NtApiDotNet" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TaskManager.UnitTests" />
    <InternalsVisibleTo Include="TaskManager.IntegrationTests" />
  </ItemGroup>

</Project>
